import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { 
  ArrowLeftIcon, 
  CheckCircleIcon,
  InformationCircleIcon,
  ClockIcon
} from "@heroicons/react/24/outline";
import Navbar from "../../components/Navbar";
import { notifySuccess } from "../../utils/notificationUtils";

export default function PaymentPage() {
  const router = useRouter();
  const { orderId, amount } = router.query;
  const [qrCode, setQrCode] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [paymentAmount, setPaymentAmount] = useState(0);
  const [isConfirming, setIsConfirming] = useState(false);

  useEffect(() => {
    const loadQRCode = async () => {
      if (!orderId && !amount) {
        setError('ไม่พบข้อมูลการสั่งซื้อ กรุณาสั่งซื้อใหม่');
        setLoading(false);
        return;
      }

      try {
        const apiUrl = process.env.NEXT_PUBLIC_API_BACKEND;
        const token = localStorage.getItem('token');

        if (!apiUrl) {
          setError('API configuration missing');
          setLoading(false);
          return;
        }

        // If orderId is provided, fetch QR code from API
        if (orderId) {
          if (!token) {
            setError('กรุณาเข้าสู่ระบบก่อน');
            setLoading(false);
            return;
          }

          const response = await fetch(`${apiUrl}/api/orders/${orderId}/qr-code`, {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${token}`,
            },
          });

          if (response.ok) {
            const data = await response.json();
            if (data.data) {
              setQrCode(data.data.qr_code);
              setPaymentAmount(parseFloat(data.data.amount));
            } else {
              setError('ไม่พบข้อมูล QR Code');
            }
          } else {
            const errorData = await response.json().catch(() => ({}));
            setError(errorData.message || 'ไม่สามารถโหลด QR Code ได้');
          }
        } else if (amount) {
          // Fallback: If only amount is provided (shouldn't happen in normal flow)
          setPaymentAmount(parseFloat(amount));
          setError('กรุณาสร้างออเดอร์ก่อนทำการชำระเงิน');
        }
      } catch (error) {
        console.error('Error loading QR code:', error);
        setError('เกิดข้อผิดพลาดในการโหลด QR Code');
      } finally {
        setLoading(false);
      }
    };

    loadQRCode();
  }, [orderId, amount]);

  const handlePaymentCompleted = async () => {
    if (!orderId) {
      router.push('/bills/BillsListPage');
      return;
    }

    if (isConfirming) return; // Prevent double-clicking

    try {
      setIsConfirming(true);
      const apiUrl = process.env.NEXT_PUBLIC_API_BACKEND;
      const token = localStorage.getItem('token');

      if (!apiUrl || !token) {
        alert('กรุณาเข้าสู่ระบบก่อน');
        setIsConfirming(false);
        return;
      }

      // Confirm payment and generate invoice
      const response = await fetch(`${apiUrl}/api/orders/${orderId}/confirm-payment`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
      });

      if (response.ok) {
        const data = await response.json();
        const orderData = data.data?.order;
        const totalAmount = orderData?.total_amount || paymentAmount;
        
        // Add success notification
        notifySuccess(
          'ชำระเงินสำเร็จ',
          `การชำระเงินสำหรับออเดอร์ #${orderId} สำเร็จแล้ว จำนวน ${parseFloat(totalAmount).toFixed(2)} บาท`
        );
        
        // Invoice will be automatically generated by backend when status changes to 'paid'
        // Redirect to bills page
        router.push(`/bills/BillPage?orderId=${orderId}`);
      } else {
        const errorData = await response.json().catch(() => ({}));
        alert(errorData.message || 'ไม่สามารถยืนยันการชำระเงินได้');
        setIsConfirming(false);
      }
    } catch (error) {
      console.error('Error confirming payment:', error);
      alert('เกิดข้อผิดพลาด กรุณาลองอีกครั้ง');
      setIsConfirming(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex flex-col">
        <Navbar showBackButton={true} />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className="w-16 h-16 border-4 border-orange-200 border-t-orange-500 rounded-full animate-spin mx-auto mb-4"></div>
            <div className="text-gray-500">กำลังโหลด QR Code...</div>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-white flex flex-col">
        <Navbar showBackButton={true} />
        <div className="flex-1 flex items-center justify-center px-4">
          <div className="text-center">
            <p className="text-red-500 text-lg mb-4">{error}</p>
            <button
              onClick={() => router.back()}
              className="px-6 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors"
            >
              กลับ
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50/30 via-white to-white flex flex-col">
      {/* Top Navigation Bar */}
      <Navbar showBackButton={true} />

      {/* Content */}
      <div className="flex-1 overflow-y-auto pb-40">
        {/* Title */}
        <div className="text-center py-8 px-4">
          <div className="flex items-center justify-center gap-2 mb-3">
            <span className="w-1 h-8 bg-gradient-to-b from-orange-500 to-orange-600 rounded-full"></span>
            <h1 className="text-3xl sm:text-4xl font-extrabold text-gray-900">ชำระเงิน</h1>
          </div>
          <p className="text-gray-600 text-sm font-medium">สแกน QR Code เพื่อชำระเงินผ่านพร้อมเพย์</p>
        </div>

        {/* Progress Indicator */}
        <div className="px-6 mb-6">
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 shadow-lg border border-gray-100">
            <div className="flex items-center justify-center">
              {/* Order Step */}
              <div className="flex flex-col items-center flex-1">
                <div className="w-12 h-12 rounded-full bg-gradient-to-br from-orange-500 to-orange-600 flex items-center justify-center mb-2 shadow-lg">
                  <CheckCircleIcon className="w-7 h-7 text-white" />
                </div>
                <span className="text-xs font-bold text-gray-700">Order</span>
              </div>
              
              {/* Connector 1 */}
              <div className="flex-1 h-1.5 bg-gradient-to-r from-orange-500 to-orange-400 mx-2 max-w-[80px] rounded-full"></div>
              
              {/* Payment Step */}
              <div className="flex flex-col items-center flex-1">
                <div className="w-12 h-12 rounded-full bg-gradient-to-br from-orange-500 to-orange-600 flex items-center justify-center mb-2 shadow-xl ring-4 ring-orange-100 animate-pulse-glow">
                  <ClockIcon className="w-7 h-7 text-white" />
                </div>
                <span className="text-xs font-bold text-orange-600">Payment</span>
              </div>
              
              {/* Connector 2 */}
              <div className="flex-1 h-1.5 bg-gray-200 mx-2 max-w-[80px] rounded-full"></div>
              
              {/* Done Step */}
              <div className="flex flex-col items-center flex-1">
                <div className="w-12 h-12 rounded-full bg-gray-200 flex items-center justify-center mb-2 border-2 border-gray-300">
                </div>
                <span className="text-xs font-bold text-gray-400">Done</span>
              </div>
            </div>
          </div>
        </div>

        {/* Payment Method Banner */}
        {/* <div className="px-6 mb-4">
          <div className="bg-gradient-to-r from-blue-700 to-blue-600 rounded-xl p-4 flex items-center gap-3 shadow-lg">
            <div className="w-12 h-12 bg-blue-500 rounded-lg flex items-center justify-center flex-shrink-0 shadow-md">
              <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2.01M19 8h2M5 20h2.01M19 20h2M12 8h.01M12 16h.01" />
              </svg>
            </div>
            <div className="flex-1">
              <span className="text-white font-bold text-lg block">THAI QR PAYMENT</span>
              <div className="flex items-center gap-2 mt-1">
                <div className="flex items-center bg-white/20 rounded px-2 py-0.5">
                  <div className="bg-blue-800 px-2 py-0.5 rounded-l">
                    <span className="text-white text-xs font-bold">Prompt</span>
                  </div>
                  <div className="bg-blue-600 px-2 py-0.5 rounded-r">
                    <span className="text-white text-xs font-bold">Pay</span>
                  </div>
                </div>
                <span className="text-blue-100 text-xs">พร้อมเพย์</span>
              </div>
            </div>
          </div>
        </div> */}

        {/* QR Code Section */}
        <div className="px-6 mb-6">
          <div className="bg-white/90 backdrop-blur-sm rounded-3xl p-8 shadow-2xl border-2 border-gray-100">
            <div className="text-center mb-6">
              <h2 className="text-xl font-bold text-gray-900 mb-2">สแกน QR Code เพื่อชำระเงิน</h2>
              <p className="text-sm text-gray-600 font-medium">เปิดแอปธนาคารของคุณและสแกน QR Code</p>
            </div>
            
            {qrCode ? (
              <div className="flex justify-center">
                <div className="bg-white p-6 rounded-3xl shadow-2xl border-4 border-gray-200 transform hover:scale-105 transition-transform duration-300">
                  <img
                    src={qrCode}
                    alt="PromptPay QR Code"
                    className="w-full max-w-[300px] mx-auto block"
                  />
                </div>
              </div>
            ) : (
              <div className="w-full max-w-[300px] mx-auto aspect-square bg-gradient-to-br from-gray-100 to-gray-200 rounded-3xl flex items-center justify-center border-4 border-dashed border-gray-300">
                <div className="text-center">
                  <div className="w-40 h-40 mx-auto bg-white border-4 border-gray-300 rounded-2xl flex items-center justify-center mb-4 shadow-inner">
                    <svg className="w-24 h-24 text-gray-400 animate-pulse" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2.01M19 8h2M5 20h2.01M19 20h2M12 8h.01M12 16h.01" />
                    </svg>
                  </div>
                  <p className="text-gray-500 text-sm font-medium">กำลังโหลด QR Code...</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Amount Card */}
        <div className="px-6 mb-6">
          <div className="bg-gradient-to-br from-orange-50 via-orange-100 to-orange-50 rounded-2xl p-6 border-2 border-orange-200 shadow-lg">
            <div className="text-center">
              <p className="text-gray-700 text-sm mb-3 font-semibold">จำนวนเงินที่ต้องชำระ</p>
              <p className="text-5xl font-extrabold bg-gradient-to-r from-orange-600 to-orange-700 bg-clip-text text-transparent mb-2">
                {paymentAmount.toFixed(2)}
              </p>
              <p className="text-xl text-gray-600 font-medium mb-3">บาท</p>
              <div className="inline-flex items-center gap-2 px-4 py-2 bg-white/80 rounded-full border border-orange-200">
                <ClockIcon className="w-4 h-4 text-orange-600" />
                <span className="text-xs text-gray-700 font-medium">กรุณาชำระเงินภายใน 15 นาที</span>
              </div>
            </div>
          </div>
        </div>

        {/* Payment Instructions */}
        <div className="px-6 mb-6">
          <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-2xl p-5 border-2 border-blue-200 shadow-md">
            <div className="flex items-start gap-3">
              <div className="p-2 bg-blue-200 rounded-lg">
                <InformationCircleIcon className="w-6 h-6 text-blue-700" />
              </div>
              <div className="flex-1">
                <h3 className="text-sm font-bold text-blue-900 mb-3">วิธีชำระเงิน</h3>
                <ol className="text-xs text-blue-800 space-y-2 list-decimal list-inside font-medium">
                  <li>เปิดแอปธนาคารหรือพร้อมเพย์บนมือถือ</li>
                  <li>เลือกเมนู "สแกน QR Code"</li>
                  <li>สแกน QR Code ที่แสดงบนหน้าจอ</li>
                  <li>ตรวจสอบจำนวนเงินและยืนยันการชำระเงิน</li>
                  <li>รอการยืนยันจากระบบ (ประมาณ 1-2 นาที)</li>
                </ol>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Action Bar */}
      <div className="fixed bottom-0 left-0 right-0 bg-white/95 backdrop-blur-md border-t-2 border-gray-200 shadow-2xl z-40 safe-area-bottom">
        <div className="p-4 space-y-3">
          {/* Next Button - After Payment Completed */}
          <button
            onClick={handlePaymentCompleted}
            disabled={!orderId || isConfirming}
            className="w-full bg-gradient-to-r from-green-500 via-green-600 to-green-700 hover:from-green-600 hover:via-green-700 hover:to-green-800 text-white font-bold py-4 rounded-xl transition-all duration-300 shadow-xl hover:shadow-2xl disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 transform hover:scale-[1.02] active:scale-[0.98]"
          >
            {isConfirming ? (
              <>
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                <span>กำลังสร้างใบแจ้งหนี้...</span>
              </>
            ) : (
              <>
                <CheckCircleIcon className="w-6 h-6" />
                <span>ชำระเงินเสร็จแล้ว - ต่อไป</span>
              </>
            )}
          </button>
          
          {/* Back Button */}
          <button
            onClick={() => router.back()}
            className="w-full bg-white hover:bg-gray-50 text-gray-700 font-semibold py-3 rounded-xl transition-all duration-300 border-2 border-gray-200 hover:border-gray-300 shadow-sm transform hover:scale-[1.01] active:scale-[0.99]"
          >
            ย้อนกลับ
          </button>
          
          <p className="text-center text-xs text-gray-500 font-medium">
            หากมีปัญหาในการชำระเงิน กรุณาติดต่อฝ่ายบริการลูกค้า
          </p>
        </div>
      </div>
    </div>
  );
}

